### ISSUE TITLE
CSV-View: Inkonsistente Deaktivierung der Combobox

### ISSUE THREAD

**Issue by LenMPorath** [whosFritz/Rail-Insights#105]
Bei Betätigung des Downloadbuttons wird manchmal die Kombobox für immer deaktiviert. Die Anzahl der Downloads die das auslöst scheint willkürlich.

Video: https://youtu.be/fzwPUIJ3tVU

**Comment by LenMPorath** [comment]
Achso, und wenn du schon dabei bist; "Download gestartet..." und "Download finished" (zwei verschiedene Sprachen) sind nicht so geil. Und Download trifft es auch nicht so wirklich, da der Download ja erst _nach_ der Verarbeitung der Daten und dem anschließenden Anzeigen des Popups gestartet wird. Bitte ebenfalls überarbeiten!

**Comment by LenMPorath** [comment]
@whosFritz

**Comment by whosFritz** [comment]
its supposed to be like that so the user changes his output. im gonna test if also activates again after time selection changed and if deactivation works in this case

**Comment by LenMPorath** [comment]
I think you miss the point here. On one hand, yes you're right; If the implementation of yours works like you described it, it's one thing. _BUT_ it doesn't make any sense that the combobox gets disabled _forever_ until you switch views or reload the page.
And what about the other points about the notifications?
Btw, i've noticed that the order of "Download gestartet..." and "Download finished" gets reversed sometimes. You can see that in the video as well.

**Comment by greybaron** [comment]
As a user of your illustrious application, this really confused me. It would appear this is a bug. We should look into this and put it on next week's agenda if necessary.

**Comment by olech2412** [comment]
changed to middle-prio because order of "Download gestartet..." and "Download finished" is sus af

**Comment by olech2412** [comment]
> I think you miss the point here. On one hand, yes you're right; If the implementation of yours works like you described it, it's one thing. _BUT_ it doesn't make any sense that the combobox gets disabled _forever_ until you switch views or reload the page. And what about the other points about the notifications? Btw, i've noticed that the order of "Download gestartet..." and "Download finished" gets reversed sometimes. You can see that in the video as well.
> 
> 🐜

i could reproduce that and it is definitely abug

**Comment by whosFritz** [comment]
Sry, all my current time is invested into Weißabgleich and SVG-Drehen. 
Gonna work on all the issues after Thursday.

**Comment by whosFritz** [comment]
> As a user of your illustrious application, this really confused me. It would appear this is a bug. We should look into this and put it on next week's agenda if necessary.

Geh scheißen

**Comment by olech2412** [comment]
i think i fixed it maybe @whosFritz could test it: https://github.com/whosFritz/Rail-Insights/tree/105-csv-view-inkonsistente-deaktivierung-der-combobox

**Comment by whosFritz** [comment]
> i think i fixed it maybe @whosFritz could test it: https://github.com/whosFritz/Rail-Insights/tree/105-csv-view-inkonsistente-deaktivierung-der-combobox

Do pr please so I see diff

**Comment by olech2412** [comment]
> > i think i fixed it maybe @whosFritz could test it: https://github.com/whosFritz/Rail-Insights/tree/105-csv-view-inkonsistente-deaktivierung-der-combobox
> 
> Do pr please so I see diff

pull branch, test it and than its ready to pr

**Comment by olech2412** [comment]
tester doesn't test so closed i dont care
