### ISSUE TITLE
NP Exception Zugstatistiken

### ISSUE THREAD

**Issue by olech2412** [whosFritz/Rail-Insights#112]
Mar  9 17:13:51 railinsights-strato java[3505]: java.lang.NullPointerException: Cannot invoke "java.lang.Integer.intValue()" because "delay" is null
Mar  9 17:13:51 railinsights-strato java[3505]: #011at de.whosfritz.railinsights.calculation.UniversalCalculator.buildDailyDelaySeries(UniversalCalculator.java:159) ~[!/:1.0.0]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at de.whosfritz.railinsights.ui.pages.TrainStatsView.createStats(TrainStatsView.java:220) ~[!/:1.0.0]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at de.whosfritz.railinsights.ui.pages.TrainStatsView.lambda$new$df5e4adf$1(TrainStatsView.java:106) ~[!/:1.0.0]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.component.ComponentEventBus.fireEventForListener(ComponentEventBus.java:239) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.component.ComponentEventBus.handleDomEvent(ComponentEventBus.java:488) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.component.ComponentEventBus.lambda$addDomTrigger$dd1b7957$1(ComponentEventBus.java:298) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.internal.nodefeature.ElementListenerMap.lambda$fireEvent$2(ElementListenerMap.java:447) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.internal.nodefeature.ElementListenerMap.fireEvent(ElementListenerMap.java:447) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.communication.rpc.EventRpcHandler.handleNode(EventRpcHandler.java:62) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.communication.rpc.AbstractRpcInvocationHandler.handle(AbstractRpcInvocationHandler.java:74) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocationData(ServerRpcHandler.java:466) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.communication.ServerRpcHandler.lambda$handleInvocations$4(ServerRpcHandler.java:447) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.communication.ServerRpcHandler.handleInvocations(ServerRpcHandler.java:447) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.communication.ServerRpcHandler.handleRpc(ServerRpcHandler.java:324) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.communication.UidlRequestHandler.synchronizedHandleRequest(UidlRequestHandler.java:114) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.SynchronizedRequestHandler.handleRequest(SynchronizedRequestHandler.java:40) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.VaadinService.handleRequest(VaadinService.java:1574) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.server.VaadinServlet.service(VaadinServlet.java:398) ~[flow-server-24.3.6.jar!/:24.3.6]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at com.vaadin.flow.spring.SpringServlet.service(SpringServlet.java:106) ~[vaadin-spring-24.3.6.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationDispatcher.invoke(ApplicationDispatcher.java:642) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationDispatcher.processRequest(ApplicationDispatcher.java:408) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationDispatcher.doForward(ApplicationDispatcher.java:313) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationDispatcher.forward(ApplicationDispatcher.java:277) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.mvc.ServletForwardingController.handleRequestInternal(ServletForwardingController.java:141) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.mvc.AbstractController.handleRequest(AbstractController.java:178) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.mvc.SimpleControllerHandlerAdapter.handle(SimpleControllerHandlerAdapter.java:51) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1089) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:979) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1014) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:914) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:590) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:885) ~[spring-webmvc-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at jakarta.servlet.http.HttpServlet.service(HttpServlet.java:658) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:205) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51) ~[tomcat-embed-websocket-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.ServerHttpObservationFilter.doFilterInternal(ServerHttpObservationFilter.java:109) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:116) ~[spring-web-6.1.4.jar!/:6.1.4]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:174) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:149) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:167) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:90) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:482) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:115) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:93) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:344) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:391) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:896) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1744) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659) ~[tomcat-embed-core-10.1.19.jar!/:na]
Mar  9 17:13:51 railinsights-strato java[3505]: #011at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:63) ~[tomcat-embed-core-10.1.19.jar!/:na]

![grafik](https://github.com/whosFritz/Rail-Insights/assets/76694468/23d43649-a528-46eb-9f07-787e1bae428f)

**Comment by whosFritz** [comment]
Gonna fix this when I'm home cause it's urgent

**Comment by olech2412** [comment]
ist mir nur beim 801er passiert

**Comment by olech2412** [comment]
there it crashes: delayByDay.computeIfAbsent(date, k -> new ArrayList<>()).add(delay >= 360 ? delay : 0);

**Comment by whosFritz** [comment]
ist mir schon klar wo, der Mac hat mir das geflüstert
