### ISSUE TITLE
Creating Cancellation View

### ISSUE THREAD

**Issue by whosFritz** [whosFritz/Rail-Insights#42]

**Comment by olech2412** [comment]
Ideen für Statistiken:
[bezieht sich alles auf den vom user gewählten Zeitraum]
- Anzahl der Ausfälle
- Aufteilung in Regional (suburban, regional, regionalExpress) und Fernverkehr (national, nationalExpress)
- Aufteilung in Zugtypen (FEX, ICE, IC, RE, REX usw.)
- Zeitlicher Verlauf der Ausfälle (wenn gewählter Zeitraum des Users größer ist als 5 Tage -> Zeige Daten als Tage an) sonst pro Tag als Stunden
- An welchem Bahnhof sind die meisten Ausfälle? Bisschen schwierig, da wenn z.B. IC xyz ausfällt der von Leipzig nach Berlin fährt in Leipzig, Berlin, Halle usw. jeweils ein Ausfall ist... vielleicht aber auch ganz interessant da ja trotzdem sichtbar ist an welchem Bhf viele trips ausgefallen sind
- Aktuelle Meldungen zu Ausfällen (kannste über Remark und Creation Date anzeigen) vielleicht als Feed oder so

**Comment by whosFritz** [comment]
erstmal auf ice gelegt. Turn up. Eiswürfel 🧊🧊❄️

**Comment by olech2412** [comment]
Da erstmal auf ice gelegt schließe ich das ganze hier
