### ISSUE TITLE
Mehrfacheinträge für Trips ab gewisser Verspätung

### ISSUE THREAD

**Issue by olech2412** [whosFritz/Rail-Insights#44]

**Comment by whosFritz** [comment]
Bin grade so mies einen versenken

**Comment by olech2412** [comment]
![Image](https://github.com/whosFritz/Rail-Insights/assets/76694468/b0863751-99e5-4200-87c2-5ff5cc236023)

Ab gößerer Verspätungen werden unterschiedliche tripIds weitergeführt für verschiedene Verspätungen (siehe Bild).

Lösungsansatz:

- Wünschenswert wäre es, wenn solche "Fehler" direkt beim Datenabruf gefunden und behoben werden (somit entstehen keine Fehler in der GUI) - ist aber wahrscheinlich relativ aufwendig
- Mindest akzeptierte Lösung - Scheduled Job der alle abgeschlossenen Trips (48h zurückblickend damit bei evtl. übersehenden trips eine gewisse überlappung da ist) auf die korrekte trip id merged. In dem Fall auf dem Bild müssten alle trips ab SchwerinHbf welche doppelt sind und nicht die größte Verspätung haben (das ist in 99,9999% die korrekte verspätung) auf die "1|198367|0|80|11022024" gemerged werden da das die korrekte und eindeutige trip id ist
