### ISSUE TITLE
CSV-Export

### ISSUE THREAD

**Issue by olech2412** [whosFritz/Rail-Insights#47]

**Comment by olech2412** [comment]
Wichtig!
https://stackoverflow.com/questions/46335449/vaadin-filedownload-requires-the-button-be-clicked-twice-to-download

**Comment by whosFritz** [comment]
Gemini:
I'd be glad to assist you with creating a download button in Vaadin that generates a CSV file containing data from a selected table, using Spring Boot's capabilities. Here's a comprehensive guide:

**1. Project Setup:**

- Ensure you have a Spring Boot project set up with Vaadin integration.
- Include the necessary dependencies, such as `opencsv`.

**2. Model and Data Provider:**

- Create an Entity/Java class to represent your table's data structure.
- Implement a Vaadin `DataProvider` to fetch and filter data for the table. This could involve accessing a database using Spring Data JPA, managing in-memory data, or any other relevant data source.

**3. Creating the Download Button:**

- In your Vaadin UI component, add a Button with appropriate text and styling (e.g., "Download CSV").
- Attach a click listener to the button using `addClickListener()`.

**4. Download Logic:**

- Inside the click listener, implement the following steps:

   - **Retrieve Selected Data:**
     - Obtain the selected items from the table using `getSelectedItems()`.
     - Alternatively, create a custom mechanism to allow users to choose specific rows or columns for download.

   - **Create CSV Content:**
     - Use the opencsv library or a similar CSV generation tool to create the CSV content as a String.
     - Iterate through the selected items and extract the desired data from each entity/object into String representations.
     - Format the data appropriately for CSV, including separators, line breaks, and any necessary escaping.

   - **Prepare the Download Stream:**
     - Set the response content type to `application/csv` using `HttpServletResponse`.
     - Set the appropriate file name using `response.setHeader("Content-Disposition", "attachment; filename=your_filename.csv")`.

   - **Write the CSV Content:**
     - Use a `ServletOutputStream` to write the CSV content to the response stream.
     - Ensure encoding is set correctly (e.g., UTF-8) to avoid character encoding issues.

**5. Example Code:**

```java
// Button click listener
button.addClickListener(event -> {
    try {
        // Get selected items (customize based on your data provider)
        List<ItemEntity> selectedItems = table.getSelectedItems();

        // Build CSV content using opencsv (replace with your preferred library)
        StringWriter csvWriter = new StringWriter();
        CSVWriter writer = new CSVWriter(csvWriter);

        // Write header row
        writer.writeNext(new String[] {"column1", "column2", "column3"});

        // Write data rows
        for (ItemEntity item : selectedItems) {
            writer.writeNext(new String[] {
                item.getColumn1Value(),
                item.getColumn2Value(),
                item.getColumn3Value()
            });
        }

        writer.close();

        // Get servlet response
        HttpServletResponse response = VaadinService.getCurrentResponse();

        // Set response headers
        response.setContentType("application/csv");
        response.setHeader("Content-Disposition", "attachment; filename=your_filename.csv");

        // Write CSV content to response stream
        response.getOutputStream().write(csvWriter.toString().getBytes());

        // Trigger download
        response.flushBuffer();
    } catch (Exception e) {
        // Handle exceptions gracefully, e.g., display error message to user
    }
});
```

**Additional Considerations:**

- Customize the CSV generation process to include only relevant columns, format data as needed, and handle potential data formatting issues.
- Consider user experience aspects like providing a progress indicator for large data exports, allowing customization of download options, and handling potential errors gracefully.
- Leverage Spring Boot's features for data access, security, and other relevant functionalities, as needed.

By following these steps and adapting the code to your specific use case, you can create an effective download button mechanism in your Vaadin application that caters to user needs and delivers CSV files accurately.

**Comment by whosFritz** [comment]
Entweder man implementiert eine toCSV methode. würde alles einfacher machen oder man macht das lazy loading anders. ich tendiere zum Ersteren ^^

**Comment by olech2412** [comment]
gucken wir uns morgen mal an wenn du magst :D

**Comment by olech2412** [comment]
Schließe ich erstmal PR ist durch. Funktion gucke ich mir morgen an :D
