### ISSUE TITLE
Readme anpassen

### ISSUE THREAD

**Issue by olech2412** [whosFritz/Rail-Insights#68]
Falsche Sachen entfernen und generell mal schick machen

**Comment by whosFritz** [comment]
adding reprography

**Comment by whosFritz** [comment]
## [![Repography logo](https://images.repography.com/logo.svg)](https://repography.com) / Recent activity [![Time period](https://images.repography.com/33848202/whosFritz/Rail-Insights/recent-activity/fxK1KNmwagTIeO43sw4ZqRAUCCarzLxyLFDCcV11_-k/Vsa8Dx0RMZ8PkC_RRfJHeTOleE-_fV1fc5Ulyepy61Q_badge.svg)](https://repography.com)
[![Timeline graph](https://images.repography.com/33848202/whosFritz/Rail-Insights/recent-activity/fxK1KNmwagTIeO43sw4ZqRAUCCarzLxyLFDCcV11_-k/Vsa8Dx0RMZ8PkC_RRfJHeTOleE-_fV1fc5Ulyepy61Q_timeline.svg)](https://github.com/whosFritz/Rail-Insights/commits)
[![Issue status graph](https://images.repography.com/33848202/whosFritz/Rail-Insights/recent-activity/fxK1KNmwagTIeO43sw4ZqRAUCCarzLxyLFDCcV11_-k/Vsa8Dx0RMZ8PkC_RRfJHeTOleE-_fV1fc5Ulyepy61Q_issues.svg)](https://github.com/whosFritz/Rail-Insights/issues)
[![Pull request status graph](https://images.repography.com/33848202/whosFritz/Rail-Insights/recent-activity/fxK1KNmwagTIeO43sw4ZqRAUCCarzLxyLFDCcV11_-k/Vsa8Dx0RMZ8PkC_RRfJHeTOleE-_fV1fc5Ulyepy61Q_prs.svg)](https://github.com/whosFritz/Rail-Insights/pulls)
[![Trending topics](https://images.repography.com/33848202/whosFritz/Rail-Insights/recent-activity/fxK1KNmwagTIeO43sw4ZqRAUCCarzLxyLFDCcV11_-k/Vsa8Dx0RMZ8PkC_RRfJHeTOleE-_fV1fc5Ulyepy61Q_words.svg)](https://github.com/whosFritz/Rail-Insights/commits)
[![Top contributors](https://images.repography.com/33848202/whosFritz/Rail-Insights/recent-activity/fxK1KNmwagTIeO43sw4ZqRAUCCarzLxyLFDCcV11_-k/Vsa8Dx0RMZ8PkC_RRfJHeTOleE-_fV1fc5Ulyepy61Q_users.svg)](https://github.com/whosFritz/Rail-Insights/graphs/contributors)
