### ISSUE TITLE
Bahnhöfe-View: Kein Padding zwischen Suchleiste und den Scroll-Div mit Bahnhofelementen

### ISSUE THREAD

**Issue by LenMPorath** [whosFritz/Rail-Insights#70]
![image](https://github.com/whosFritz/Rail-Insights/assets/125283275/0b581a4b-4ffe-4cb8-b7f8-7db22fd56b91)

Das Div mit den Bahnhof-Elementen ist nicht gepadded zur Suchleiste. Wenn man anfängt zu scrollen "klebt" das oberste Bahnhof-Element quasi an der Suchleiste:

![image](https://github.com/whosFritz/Rail-Insights/assets/125283275/85029052-1a63-49ab-b923-19152110775f)

Darüber hinaus ist die Suchleiste ungleich der Breite des darunter liegenden Divs. Die Breite sollte man also auch anpassen.

**Comment by whosFritz** [comment]
ersten Punkt mache ich, zweiten Punkt Darstellung selber machen

**Comment by LenMPorath** [comment]
mach dein projekt selber
