### ISSUE TITLE
Wrong calculation in Zugstatistiken

### ISSUE THREAD

**Issue by olech2412** [whosFritz/Rail-Insights#93]
Example ICE 929:
![grafik](https://github.com/whosFritz/Rail-Insights/assets/76694468/ef3478b2-c622-4210-b888-98b76cf93d70)

delay is tooo high, because duplicates are not filtered or not filtered correctly:
![grafik](https://github.com/whosFritz/Rail-Insights/assets/76694468/cee55253-d1e3-4940-8e9c-194479afd60c)

**Comment by olech2412** [comment]
I think this is something bigger because here the trips are filtered but the real delay (the highest value) is not displayed only the initial one:
![grafik](https://github.com/whosFritz/Rail-Insights/assets/76694468/bae7d0c8-7cc3-49f2-b394-056bc146dae2)

**Comment by olech2412** [comment]
i dont think the values display there are minutes

**Comment by whosFritz** [comment]
gonna fix that tomorrow in university (behindertenschule)

**Comment by olech2412** [comment]
> gonna fix that tomorrow in university (behindertenschule)

probably partly fixed: https://github.com/whosFritz/Rail-Insights/pull/94
